import{a as L,S as v,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&u(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const w="39486318-698ac6813de625d5bba6b85f3",B="https://pixabay.com/api/";async function f(s,o){return(await L.get(B,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const p=document.getElementById("gallery"),m=document.getElementById("loader"),h=document.getElementById("load-more");let E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const o=s.map(e=>`
      <div class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>
    `).join("");p.insertAdjacentHTML("beforeend",o),E.refresh()}function I(){p.innerHTML=""}function g(){m.classList.remove("is-hidden")}function c(){m.classList.add("is-hidden")}function P(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const M=document.getElementById("search-form"),R=document.getElementById("load-more");let n=1,l="",d=0;M.addEventListener("submit",async s=>{s.preventDefault();const o=s.currentTarget.elements.searchQuery.value.trim();if(o){l=o,n=1,I(),b(),g();try{const e=await f(l,n);if(d=e.totalHits,e.hits.length===0){a.info({message:"No images found. Try another query.",position:"topRight"}),c();return}y(e.hits),d>15&&P()}catch{a.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{c()}}});R.addEventListener("click",async()=>{n+=1,g();try{const s=await f(l,n);y(s.hits);const o=Math.ceil(d/15);n>=o&&(b(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{a.error({message:"An error occurred. Please try again later.",position:"topRight"})}finally{c()}});
//# sourceMappingURL=index.js.map
